### ISSUE TITLE
Description for input data

### ISSUE THREAD

**Issue by hasbishiddiqi** [mmesim/Vp_Vs_diff_times#1]
Dear Dr.  Maria Mesimeri,

Thank you for sharing the code.

I am interested to apply this code to study the Vp/Vs variation of a seismic swarm sequence. Can you please provide description for the input data (results_xcorr.mat and test.txt)?

Best regards,

Hasbi

**Comment by mmesim** [comment]
Hi @hasbishiddiqi!

Thanks for opening this issue. I understand that the current version of the code lacks documentation. I'll try to solve this issue as soon as possible. 

Thanks!

**Comment by hasbishiddiqi** [comment]
Thank you!

Looking forward for the documentation.

Regards,

Hasbi

**Comment by mmesim** [comment]
@hasbishiddiqi 

I updated the documentation (https://github.com/mmesim/Vp_Vs_diff_times). Please also check here

https://github.com/mmesim/Vp_Vs_diff_times/blob/c664d54210c84f784f87600ccfa6bda1263cd634/Vp_Vs_cc_times.m#L12-L28


I also added a new repository -> https://github.com/mmesim/relative_loc/tree/main/xcorr which contains the scripts I use to calculate cross correlation diff. times. the output from that code is the input for https://github.com/mmesim/Vp_Vs_diff_times .

**Comment by hasbishiddiqi** [comment]
Dear @mmesim,

Thank you for adding the documentation and the necessary scripts.

Hasbi

**Comment by cup-tjh** [comment]
Dear Dr. Maria Mesimeri,

Thank you for sharing the code.

I don't konow how you calculate the 'TIME RALTIVE TO THE FIRST EVENT IN THE CATALOG'.I don't know what its units are.Can you tell me more about it?

Best regards,
JH

**Comment by mmesim** [comment]
Time relative to first event means that you subtract the date the first event from the later events. 

Usually the unit is seconds. A built-in matlab function is [datenum](https://ch.mathworks.com/help/matlab/ref/datenum.html) for earlier versions of matlab, or [datetime](https://ch.mathworks.com/help/matlab/ref/datetime.html).

**Comment by cup-tjh** [comment]
Thank you !


> 相对于第一个事件的时间意味着从后面的事件中减去第一个事件的日期。
> 
> 通常单位是秒。对于早期版本的 matlab，内置的 matlab 函数是 [datenum](https://ch.mathworks.com/help/matlab/ref/datenum.html) 或 [datetime](https://ch.mathworks.com/help/matlab/ref/datetime.html)。
